#!/bin/sh
#SUBALL for electra

stime="5m"
xshelldist=3.1
inputfile=$1
jobname=sub-$1-$RANDOM
infile=freq.inp
outfile=freq.log

#SCRIPT 1
if [[  $(grep "Normal t" ${inputfile}-dir/${outfile} -s | wc -l)  == 0 ]]; then
mkdir $inputfile-dir
cd $inputfile-dir
cp ../G.TXT .

if [ -f ../AFTER.GEN.TXT ]; then
cp ../AFTER.GEN.TXT AFTER.TXT
touch GAUS_GEN_BASIS
else
#cp ../AFTER.TXT . 2>/dev/null
cp ../AFTER.TXT . | true
fi

cp ../XSHELL.OPT .
cp ../$inputfile FILE.X
xshell $xshelldist
mv NEWFILE.X FILE.X
xinp
mv FILE.INP $infile

natoms=$(( $(wc -l < FILE.X) - 2))
if [ -f GAUS_GEN_BASIS ]; then
sed -i "s/lastatom/${natoms}/" $infile
fi

#subg16 freq.inp

else
echo "SKIPPING PART 1 - Frequencies"
cd $inputfile-dir
if [ -f ../AFTER.GEN.TXT ]; then
cp ../AFTER.GEN.TXT AFTER.TXT
touch GAUS_GEN_BASIS
fi
natoms=$(( $(wc -l < FILE.X) - 2))
fi
abspath=`pwd`
abspath=/share/`echo $abspath | cut -d "/" -f3-`


#SCRIPT 2
queue="long"
nproc=4
if [[ $(grep "Converged" nmode/QGRAD.OUT -s | wc -l)  == 0 ]]; then
mkdir nmode
cd nmode
cp ../../Q.OPT .
cp ../../Gmode.TXT G.TXT
cp ../AFTER.TXT . | true

else
echo "SKIPPING PART 2 - Optimization"
cd nmode
fi
DIRNAME=`pwd`
#jobname=`echo ${DIRNAME##*/}`
export WDIR=/share/`echo $DIRNAME | cut -d "/" -f3-`


#SCRIPT 3, 4
if [[ $(grep "Normal t" roa/roa.log -s | wc -l)  == 0 ]]; then
mkdir roa
cd roa
cp ../../../ROA.OPT .
cp ../../../EA.LST .

else
echo "SKIPPING PART 3 - Final frequencies"
cd roa
fi
FDIRNAME=`pwd`
export FDIR=/share/`echo $FDIRNAME | cut -d "/" -f3-`

cd ../..


cat <<END  >>$jobname.bsh
#!/bin/bash
#$ -q $queue
#$ -l num_proc=$nproc
#$ -S /bin/bash
#$ -N $jobname
#$ -o $abspath/out
#$ -j y
#$ -r no
#$ -c n
#$ -V
#$ -pe cre $nproc


#SUB RUN 1 = (subg16)
export SCRPATH=/scratch/\$LOGNAME
export SCRATCHDIR=/scratch/\$LOGNAME/\$JOB_NAME.\$JOB_ID
mkdir \$SCRATCHDIR
cd \$SCRATCHDIR
# pripravime si vstupni soubor, napr. do adresare /scratch
cp $abspath/* \$SCRATCHDIR

uname -n > MACHINE.LOG
cp MACHINE.LOG $abspath/

if [[  \$(grep "Normal t" $outfile -s | wc -l)  == 0 ]]; then

/usr/local/g16-A.03/g16 $infile $outfile
cp freq.log $abspath/
fi


#SUB RUN 2 = (subqgrad16)
export LD_LIBRARY_PATH=""
export PATH=/bin:/usr/bin:/usr/local/bin:/share/bour/New:/share/\$LOGNAME/bin
#export g16root=/usr/local/G16B
#source \$g16root/g16/bsd/g16.profile
#export WDIR=/share/`pwd | cut -d "/" -f3-`
mkdir nmode
export CMPDIR=\$SCRPATH/\$JOB_NAME.\$JOB_ID/nmode

cp $abspath/nmode/* \$CMPDIR/
if [[  \$(grep "Converged" \$CMPDIR/QGRAD.OUT -s | wc -l)  == 0 ]]; then

cp freq.log FRE.OUT
cp FRE.OUT G98.OUT
touch AUTO
/share/zikes/scripts/gar9
#cd \$CMPDIR
cd nmode
cp ../FILE.* .
/share/zikes/scripts/xinp
mv FILE.INP G98.INP

if [ -f ../GAUS_GEN_BASIS ]; then
sed -i "s/lastatom/$natoms/" G98.INP
fi

/share/zikes/scripts/new1
printf "0\n0\ny" | /share/zikes/scripts/new2

#cd \$CMPDIR/
#Schell script driving the optimization in normal modes
#Starting point - frequencies must be calculated
#and F.INP or FILE.FC and FTRY.INP present

#g98 G98.INP G98.OUT
/usr/local/g16-A.03/g16 G98.INP G98.OUT
/share/zikes/scripts/qgrad

while [ -f "INP.NEW" ]; do

 mv INP.NEW G98.INP
 cp G98.OUT G98.OUT.last
#g98 G98.INP G98.OUT
 /usr/local/g16-A.03/g16 G98.INP G98.OUT
 /share/zikes/scripts/qgrad

done

cp G98.OUT $abspath/nmode/
#cp -r \$CMPDIR/* \$WDIR/ && rm -rf \$CMPDIR && echo "OK"

else
cd nmode
fi


#SUB RUN 3 = (subg16)
mkdir roa
cd roa
if [[  \$(grep "Normal t" $abspath/nmode/roa/roa.log -s | wc -l)  == 0 ]]; then
cp ../G98.INP roa.inp
sed -i "s/force/freq=(roa,vcd)/" roa.inp
sed -i "/guess=checkpoint/d" roa.inp
sed -i "s/mem=4GB/mem=8GB/" roa.inp

if [ -f ../../GAUS_GEN_BASIS ]; then
sed -i "s/1-16 0/532 nm\n\n1-16 0/" roa.inp
else
echo "532 nm" >> roa.inp
echo " " >> roa.inp
fi

/usr/local/g16-A.03/g16 roa.inp roa.log
cp roa.log $abspath/nmode/roa/
fi

#SUB RUN 4
cp $abspath/nmode/roa/* .
cp roa.log FRE.OUT
touch AUTO
/share/zikes/scripts/gar9
/share/zikes/scripts/new1
printf "0\n0\ny" | /share/zikes/scripts/new2
/share/zikes/scripts/new4
/share/zikes/scripts/eattt
/share/zikes/scripts/new5
/share/zikes/scripts/new6
/share/zikes/scripts/filter
cd ../../..

#COPY THE FILES BACK
cp -r \$SCRATCHDIR/* $abspath/ && rm -rf \$SCRATCHDIR && echo "OK"
#cp -r \$SCRATCHDIR/* $abspath/ && echo "OK"

END

qsub $jobname.bsh
cd ..

