#!/bin/sh
#SUBALL for lenka

stime="5m"
xshelldist=0
inputfile=$1
jobname=sub-$1-$RANDOM
infile=freq.inp
outfile=freq.log

#SCRIPT 1
mkdir $inputfile-dir
cd $inputfile-dir
abspath=`pwd`
abspath=/share/`echo $abspath | cut -d "/" -f3-`
cp ../G.TXT .
cp ../XSHELL.OPT .
cp ../$inputfile FILE.X
xshell $xshelldist
mv NEWFILE.X FILE.X
xinp
mv FILE.INP $infile
#subg16 freq.inp


#SCRIPT 2
queue="long"
nproc=4
mkdir nmode
cd nmode
cp ../../Q.OPT .
cp ../../Gmode.TXT G.TXT
DIRNAME=`pwd`
#jobname=`echo ${DIRNAME##*/}`
export WDIR=/share/`echo $DIRNAME | cut -d "/" -f3-`


#SCRIPT 3
mkdir roa
cd roa
cp ../../../ROA.OPT .
cp ../../../EA.LST .
FDIRNAME=`pwd`
export FDIR=/share/`echo $FDIRNAME | cut -d "/" -f3-`

cd ../..


cat <<END  >>$jobname.bsh
#!/bin/bash
#$ -q $queue
#$ -S /bin/bash
#$ -N $jobname
#$ -o $WDIR/out
#$ -j y
#$ -r no
#$ -c n
#$ -V
#$ -pe cre $nproc


#SUB RUN 1 = (subg16)
export SCRPATH=/scratch/\$LOGNAME
export SCRATCHDIR=/scratch/\$LOGNAME/\$JOB_NAME.\$JOB_ID
mkdir \$SCRATCHDIR
cd \$SCRATCHDIR
# pripravime si vstupni soubor, napr. do adresare /scratch
cp $abspath/* \$SCRATCHDIR

/usr/local/g16-A.03/g16 $infile $outfile
cp freq.log $abspath/

#SUB RUN 2 = (subqgrad09)
export LD_LIBRARY_PATH=""
export PATH=/bin:/usr/bin:/usr/local/bin:/share/bour/New:/share/\$LOGNAME/bin
export g03root=""
export g09root=/usr/local/G09A02_em64t
source \$g09root/g09/bsd/g09.profile
#export WDIR=/share/`pwd | cut -d "/" -f3-`
mkdir nmode
export CMPDIR=\$SCRPATH/\$JOB_NAME.\$JOB_ID/nmode

cp $abspath/nmode/* \$CMPDIR/
cp freq.log FRE.OUT
cp FRE.OUT G98.OUT
touch AUTO
/share/zikes/scripts/gar9
#cd \$CMPDIR
cd nmode
cp ../FILE.* .
/share/zikes/scripts/xinp
mv FILE.INP G98.INP
/share/zikes/scripts/new1
printf "0\n0\ny" | /share/zikes/scripts/new2

#cd \$CMPDIR/
#Schell script driving the optimization in normal modes
#Starting point - frequencies must be calculated
#and F.INP or FILE.FC and FTRY.INP present

#g98 G98.INP G98.OUT
g09 G98.INP G98.OUT
/share/bour/New/qgrad

while [ -f "INP.NEW" ]; do

 mv INP.NEW G98.INP
 cp G98.OUT G98.OUT.last
#g98 G98.INP G98.OUT
 g09 G98.INP G98.OUT
 /share/bour/New/qgrad

done

cp G98.OUT $abspath/nmode/
#cp -r \$CMPDIR/* \$WDIR/ && rm -rf \$CMPDIR && echo "OK"

#SUB RUN 3 = (subg16)
mkdir roa
cd roa
cp ../G98.INP roa.inp
sed -i "s/force/freq=(roa,vcd)/" roa.inp
sed -i "/guess=checkpoint/d" roa.inp
sed -i "s/mem=4GB/mem=8GB/" roa.inp
echo "532 nm" >> roa.inp
echo " " >> roa.inp
/usr/local/g16-A.03/g16 roa.inp roa.log
cp roa.log $abspath/nmode/roa/

#SUB RUN 4
cp $abspath/nmode/roa/* .
cp roa.log FRE.OUT
touch AUTO
/share/zikes/scripts/gar9
/share/zikes/scripts/new1
printf "0\n0\ny" | /share/zikes/scripts/new2
/share/zikes/scripts/new4
/share/zikes/scripts/eattt
/share/zikes/scripts/new5
/share/zikes/scripts/new6
/share/zikes/scripts/filter
cd ../../..

#COPY THE FILES BACK
#cp -r \$SCRATCHDIR/* $abspath/ && rm -rf \$SCRATCHDIR && echo "OK"
cp -r \$SCRATCHDIR/* $abspath/ && echo "OK"

END

qsub $jobname.bsh
cd ..

